kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: bitcoin-core-storage-class
  annotations: {}
provisioner: alicloud/disk
reclaimPolicy: Retain
parameters:
  type: cloud_ssd
  fstype: "ext4"
  readonly: "false"
allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer