apiVersion: v1
kind: Service
metadata:
  name: bitcoin
  namespace: bitcoin-core
spec:
  ports:
    - port: 8333
      targetPort: 8333
  selector:
    service: bitcoin
  type: ClusterIP
  #externalTrafficPolicy: Local