apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-core-config
  namespace: bitcoin-core
data:
  bitcoin-config: |
    printtoconsole=1
    rpcallowip=::/0
    dbcache=4096
    checkblocks=7
    blockmaxsize=8000000
    maxconnections=500
    zmqpubrawblock=tcp://127.0.0.1:28333
    rpcpassword=changeme
    rpcuser=rpcuser
